<a href="https://ondiande.com/contact/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="ONDIA Contact" width="110" height="200" title="This notebook is licensed by ONDIA. Please contact the authorized persons about the conditions under which you can use or share."></a>

<div style="background-color:#8CCED1; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;"></div>

<p style="text-align: center;"> <a href="https://ondiande.com/"> <img src="https://i.ibb.co/mvHRT4S/ONDIA-logo.png" width="500" height="200" class="img-fluid" alt="ONDIA LOGO" title="INTELLIGENT & PERSONALIZED SOLUTIONS TO DATA ANALYSIS AND DATA MANAGEMENT ISSUES"> </a> </p>

<div style="background-color:#58B8E4; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;">
  Intelligent & Personalized Solutions
</div>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:300%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

<div style="background-color:#8CCED1; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;"></div>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<div style="background-color:#58B8E4; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;"></div>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [83]:
import numpy as  np



### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [85]:
np.arange(5,26,5)

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros.

In [87]:
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [89]:
np.ones((4,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [101]:
arr = np.ones((4, 4), dtype=int)*7
print(arr)



[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


### 6. Create the previous array above by full() method.

In [18]:
np.full((4,4), 7, dtype=int)
arr



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive).

In [20]:

np.arange(2,17,2)




array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [22]:
np.arange(25).reshape(5,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [24]:
array = np.linspace(0,24, num=25).reshape(5,5)
array



array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

### 10. Create randomly 5 numbers with numpy.

In [26]:
np.random.randn(5)



array([ 1.8359699 , -0.77414996, -1.72457652,  0.63545069, -0.15644969])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [28]:
np.random.randn(5,5)



array([[ 0.13341298, -0.5573035 , -0.78347876,  0.05989073, -0.79209905],
       [ 0.22543126, -1.17735153, -0.2505924 , -1.2048774 , -1.22887558],
       [ 0.51170984,  0.30855108, -1.30008714,  0.66675703,  0.61982418],
       [-0.28590719, -1.86130104, -0.85927958,  0.4868306 ,  0.8198236 ],
       [-1.68065824,  0.25906446,  0.8834493 ,  1.16141705, -0.69107324]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [30]:
np.random.randint(20,51, size=(3,4))



array([[37, 46, 23, 40],
       [26, 48, 24, 26],
       [35, 44, 27, 31]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [32]:
ranarr = np.random.randint(1,48,48)
ranarr


array([47,  9, 37, 23, 36,  1, 37,  8, 41, 32, 37, 39, 30,  8, 38, 13,  3,
       27, 29, 13, 32, 25,  7, 41,  3, 44, 45, 31, 15, 11, 19, 32, 27, 14,
       32, 13, 13,  3, 43, 17, 44, 35, 34,  4, 20,  3, 43, 33])

In [33]:
ranarr = np.random.randint(0,48,48).reshape(6,8)
ranarr



array([[11, 39, 11, 12, 29, 10, 44, 21],
       [16, 28, 23, 41, 13,  5, 22, 10],
       [25, 10, 18, 35,  0, 20, 43, 35],
       [45, 40,  9, 31, 42,  0, 14, 24],
       [ 0, 12, 13, 19, 45, 38,  3, 37],
       [40, 31, 21, 46, 46, 23,  8, 25]])

In [34]:
# (RESHAPING WITH -1)

ranarr = np.random.randint(0,48,48).reshape(6,-1)
ranarr



array([[42, 31, 28, 36, 32,  3, 35, 28],
       [24, 29, 29, 23, 16,  9, 35, 30],
       [ 7,  7, 31, 23, 26, 41, 26, 35],
       [34,  7, 11,  2, 25, 17, 41, 29],
       [25,  8, 14, 30,  0, 19,  3, 29],
       [34, 26, 18, 26, 32, 15,  8, 27]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [38]:
mat = np.arange(1,17).reshape(4,4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [40]:
mat[1:3, 1:3] 


array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [42]:
mat[0:4, 0]


array([ 1,  5,  9, 13])

In [43]:
mat[:, 0]

array([ 1,  5,  9, 13])

In [105]:
#16. Get the values in 2nd row (index number 1) for every 2 step
mat[1:3:2, 0:3:2]      

array([[5, 7]])

In [ ]:
Desired Output:

array([5, 7])       

### 17.Assign 77 to every cell in 3rd column.

In [107]:
mat[:,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [109]:
mat[1:3:2, 0:3:2]

array([[ 5, 77]])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [111]:
mat[1,1:2]
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

## NumPy Operations

In [115]:
20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".¶
mat[:,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [117]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat"

 
mat[mat < 10]



array([1, 2, 4, 5, 6, 8, 9])

In [119]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat"

mat[mat > 12]




array([77, 77, 77, 13, 14, 77, 16])

In [121]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat"

mat[mat < 10] + mat[mat > 12]



array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [123]:
# YOUR CODE IS HERE
np.std(mat)



30.004166377354995

### 22. Get the sum of the 2nd column in the original "mat".

In [125]:
# LET US REMEMBER OUR ARRAY OF "mat"
mat[:,2] = 77
mat




array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [127]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat"

mat = np.arange(1,17).reshape(4,4)
mat



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [129]:
np.sum(mat[:,1])
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 23. Get the median, mean and std of 3rd column in "mat".

In [131]:
# LET US REMEMBER OUR ARRAY OF "mat"

mat = np.arange(1,17).reshape(4,4)
mat



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [147]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE

mat[:2,  axis==1]
mat



NameError: name 'axis' is not defined

In [ ]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW?
mat[2,:]



In [ ]:
# LET US GET MEDIAN VALUE

np.median(mat[2:,])        

In [ ]:
np.median(mat[:,2])

In [ ]:
# LET US GET MEAN VALUE

np.mean(mat)



In [ ]:
# LET US GET STANDART DEVIATION (std) VALUE

np.std(mat)


In [ ]:
np.std(mat axis=1)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [159]:
import pandas as pd
import numpy as np


### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [161]:
# LET US READ Salarie
df0 = pd.read_csv("Salaries.xls")
df0


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [ ]:
# LET US LOOK AT THE FIRST 5 ROWS

df0.head(5)



Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
# LET US GET A SAMPLE
df0.sample()



In [ ]:
# LET US GET A SAMPLE
df0.sample()



Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [163]:
df0.info()
df0



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS

df0.describe()



Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
df0.Year.unique()   

In [ ]:
df0.Year.value_counts()

In [ ]:
df0

In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"
df0.Year.nunique()


In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

df0["Year"].value_counts().array  



In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

df0["Year"].unique() 



In [165]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

df0["Year"].unique() 
df0



Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

### Print out max and avg values in the column of "Totalpay".

In [ ]:
# LET US FIND THE MAXIMUM TOTALPAY
df0['TotalPay'].max()


In [ ]:
# LET US FIND THE AVERAGE TOTALPAY
                                     
mean_TotalPay = df0['TotalPay'].mean()
mean_TotalPay


### How many records in the TotalPay column are there bigger than avg TotalPay?

In [ ]:
count_above_mean = (df0['TotalPay'] > mean_TotalPay).sum()
count_above_mean



Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
count_above_mean = (df0['TotalPay'] > mean_TotalPay).sum()
count_above_mean



### How much does ALBERT PARDINI make money (including benefits)?

In [ ]:
df0[df0.EmployeeName == 'ALBERT PARDINI']['TotalPayBenefits']
            


### Who is the lowest paid person?

In [ ]:
df0[df0.TotalPayBenefits == df0.TotalPayBenefits.min()]['EmployeeName']

In [ ]:
lowest_paid_employee = df0["EmployeeName"]
lowest_paid_salary

### What are the unique Jobs in dataset?

In [ ]:
df0['JobTitle'].unique()



### List the top 3 least common Jobs in the dataset.

In [ ]:
least_common_jobs = df0['JobTitle'].value_counts().tail(3)
least_common_jobs
                                       

### How many people earned more than avg in 2012?

In [ ]:
df0[(df0.Year == 2012)]['EmployeeName'].count()

In [ ]:
df0.TotalPayBenefits.mean()

In [ ]:
df0[(df0.TotalPayBenefits > df0.TotalPayBenefits.mean())]

### How many people have a title of Manager in their jobs?

In [ ]:
df0['JobTitle'] == 'manager'

In [ ]:
manager_sayisi = (df0['JobTitle'] == 'Manager').sum()
manager_sayisi

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
df0.head(1)

In [ ]:
 # Id = 0, EmployeeName = 1, JobTitle = 2, TotalPay = 7, TotalPayBenefits = 8
df0.iloc[:, [0, 1, 2, 7, 8]]


Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
df0.loc[:, [ 'EmployeeName','JobTitle','TotalPayBenefits','TotalPayBenefits']]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
min_salary = df0['TotalPayBenefits'].min()
min_salary

In [ ]:
avg_salary = df0['TotalPayBenefits'].mean()
avg_salary 

In [ ]:
EmployeeName = df0[(df0['TotalPayBenefits'] > min_salary) & (df0['TotalPayBenefits'] < avg_salary)]
EmployeeName
df0[['EmployeeName', 'TotalPayBenefits']]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<hr>

<p style="background-color:#FDFEFE; font-family:newtimeroman; color:#635EA7; font-size:350%; text-align:center; border-radius:10px 10px;">End of The Assignment - 1</p>

# <span style="color:#DA55E5">**Now. it's time to relax!**<span>
    
![Image_Assignment](https://i.ibb.co/jZD3Mqb/relaxing.jpg)
   

<a href="https://ondiande.com/contact/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="ONDIA Contact" width="110" height="200" title="This notebook is licensed by ONDIA. Please contact the authorized persons about the conditions under which you can use or share."></a>